[ MOSIP-24334 ] updated workflows and README.md file

diff --git a/.github/workflows/helm-lint-manual.yaml b/.github/workflows/helm-lint-manual.yaml
--- a/.github/workflows/helm-lint-manual.yaml
+++ b/.github/workflows/helm-lint-manual.yaml
@@ -41,55 +41,83 @@ jobs:
 
       - name: Set environment variables
         run: |
+          # echo "TARGET BRANCH : ${{ github.event.inputs.target_branch }}"
           echo "TARGET_BRANCH=$(echo ${{ github.event.inputs.target_branch }} )" >> $GITHUB_ENV
+          echo "COMMIT_ID=${GITHUB_SHA}" >> $GITHUB_ENV
           echo "TARGET_REPO=$( echo ${{ github.event.inputs.target_repo }} )" >> $GITHUB_ENV
 
       - name: Add Target repo to git remotes
-        run: | 
+        run: |
           git remote add target_repo $TARGET_REPO
           git fetch target_repo
 
       - name: Set up chart-testing
         uses: helm/chart-testing-action@v2.3.1
 
-      - name: Run chart-testing (list-changed)
-        id: list-changed
-        run: |
-          ct list-changed --remote=target_repo --since=HEAD --target-branch=$TARGET_BRANCH --chart-dirs=charts | tee -a list.txt 
-
       - name: Run chart-testing (lint)
-        run: |          
-          while read -r chart; do
-            echo "CHART: $chart";
-            ct lint --config=.github/chart-testing-config.yaml --charts=$chart/ --remote=target_repo;
-          done < ./list.txt
+        run: |
+          ls -d charts/* > list.txt;
+          ct lint --config=.github/chart-testing-config.yaml --chart-dirs=charts --remote=target_repo --target-branch=$TARGET_BRANCH;
 
-      - name: Create deploy / statefulset yaml
+      - name: Create yaml files for helm charts
         run: |
           while read -r chart; do
             echo -e "\nCHART: $chart\n";
-            
-            ls $chart/templates/ | grep -E '*deploy*|*statefulset*' > yaml_list;
+          
+            yaml_file='./chart-template.yaml'
             chart_name=$( echo $chart | awk -F / '{print $2}' );
-            
             mkdir "$chart_name-yaml";
-            
-            while read -r yaml; do
-              helm template $chart -s templates/$yaml > "$chart_name-yaml"/$yaml;
-            done < ./yaml_list
-            
+          
+            helm template $chart > $yaml_file
+            last_line=$( cat -n $yaml_file| tail -n 1 | awk '{print $1}' )
+            line_nos="$( cat -n $yaml_file | awk '/---/{print $1}' ) $last_line"
+            start_of_file=0
+          
+            for line in $line_nos; do
+              if [[ $line -eq 1 ]]; then
+                start_of_file=$line;
+                continue;
+              fi
+          
+              head_line=$(( line-1 ));
+              tail_line=$(( line-start_of_file ));
+          
+              if [[ $line -eq $last_line ]]; then
+                head_line=$line;
+                tail_line=$(( line-start_of_file+1 ));
+              fi
+          
+              start_of_file=$line;
+              # echo "HEAD LINE: $head_line, TAIL LINE: $tail_line";
+          
+              yaml_type=$( head -n +$head_line $yaml_file | tail -n $tail_line | grep -c -E "kind\:\ Deployment|kind\:\ StatefulSet" || true );  # used "true" to return exit code as 0
+              # echo "YAML TYPE: $yaml_type";
+              if [[ "$yaml_type" -eq 0 ]]; then
+                 # echo "if YAML TYPE: $yaml_type";
+                 continue;
+              fi
+          
+              filename=$( head -n +$head_line $yaml_file | tail -n $tail_line | awk -F '/' '/# Source/{print $3}' );
+              echo "$filename";
+              head -n +$head_line $yaml_file | tail -n $tail_line > "$chart_name-yaml/$filename";
+            done
           done < ./list.txt
 
       - name: Run Health Check Test
         run: |
           while read -r chart; do
-            echo -e "\nCHART: $chart\n";
+            echo -e "\n\nCHART: $chart\n";
+          
             chart_name=$( echo $chart | awk -F / '{print $2}' );
-            
-            while read -r yaml; do
-              echo "YAML : $yaml";
-              yamale -s .github/health-check-schema.yaml $chart_name-yaml/$yaml  --no-strict
-            done <<< $( ls "$chart_name-yaml" ) 
+            list=$( ls $chart_name-yaml );
+          
+            echo -e "YAML LIST :";
+            echo -e "$list\n"
+          
+            for yaml in $list; do
+              echo -e "YAML : $yaml";
+              yamale -s .github/health-check-schema.yaml "$chart_name-yaml/$yaml" --no-strict
+            done
           
           done < ./list.txt
 
diff --git a/.github/workflows/helm-lint.yaml b/.github/workflows/helm-lint.yaml
--- a/.github/workflows/helm-lint.yaml
+++ b/.github/workflows/helm-lint.yaml
@@ -51,7 +51,7 @@ jobs:
           ct list-changed --remote=target_repo --since=HEAD --target-branch=$TARGET_BRANCH --chart-dirs=charts | tee -a list.txt 
 
       - name: Run chart-testing (lint)
-        run: |          
+        run: |
           while read -r chart; do
             echo "CHART: $chart";
             ct lint --config=.github/chart-testing-config.yaml --charts=$chart/ --remote=target_repo;
@@ -61,25 +61,44 @@ jobs:
         run: |
           while read -r chart; do
             echo -e "\nCHART: $chart\n";
-            
+                  
             yaml_file='./chart-template.yaml'
             chart_name=$( echo $chart | awk -F / '{print $2}' );
             mkdir "$chart_name-yaml";
-            
+                 
             helm template $chart > $yaml_file
-            line_nos="$( cat -n $yaml_file | awk '/---/{print $1}' ) $( cat -n $yaml_file| tail -n 1 | awk '{print $1}' )"
+            last_line=$( cat -n $yaml_file| tail -n 1 | awk '{print $1}' )
+            line_nos="$( cat -n $yaml_file | awk '/---/{print $1}' ) $last_line"
             start_of_file=0
             
             for line in $line_nos; do
               if [[ $line -eq 1 ]]; then
+                start_of_file=$line;
                 continue;
-                start_of_file=$line
               fi
-              filename=$( head -n +$(( line-1)) $yaml_file | tail -n $(( line-start_of_file )) | awk -F '/' '/# Source/{print $3}' )
-              head -n +$(( line-1 )) $yaml_file | tail -n $(( line-start_of_file )) > "$chart_name-yaml"/$filename
-              start_of_file=$line
+              
+              head_line=$(( line-1 ));
+              tail_line=$(( line-start_of_file ));
+              
+              if [[ $line -eq $last_line ]]; then
+                head_line=$line;
+                tail_line=$(( line-start_of_file+1 ));
+              fi
+              
+              start_of_file=$line;
+              # echo "HEAD LINE: $head_line, TAIL LINE: $tail_line";
+              
+              yaml_type=$( head -n +$head_line $yaml_file | tail -n $tail_line | grep -c -E "kind\:\ Deployment|kind\:\ StatefulSet" || true );  # used "true" to return exit code as 0
+              # echo "YAML TYPE: $yaml_type";
+              if [[ "$yaml_type" -eq 0 ]]; then
+                 # echo "if YAML TYPE: $yaml_type";
+                 continue;
+              fi
+              
+              filename=$( head -n +$head_line $yaml_file | tail -n $tail_line | awk -F '/' '/# Source/{print $3}' );
+              echo "$filename";
+              head -n +$head_line $yaml_file | tail -n $tail_line > "$chart_name-yaml/$filename";
             done
-            
           done < ./list.txt
 
       - name: Run Health Check Test
@@ -88,15 +107,15 @@ jobs:
             echo -e "\n\nCHART: $chart\n";
             
             chart_name=$( echo $chart | awk -F / '{print $2}' );
-            list=$( grep -rinlE "kind:\ Statefulset|kind:\ Deployment" $chart_name-yaml );
+            list=$( ls $chart_name-yaml );
             
             echo -e "YAML LIST :";
             echo -e "$list\n"
             
-            while read -r yaml; do
+            for yaml in $list; do
               echo -e "YAML : $yaml";
-              yamale -s .github/health-check-schema.yaml $yaml  --no-strict
-            done <<< $list
+              yamale -s .github/health-check-schema.yaml "$chart_name-yaml/$yaml" --no-strict
+            done
           
           done < ./list.txt
 
