[MOSIP-27511]
Signed-off-by: Rakshitha650 <76676196+Rakshitha650@users.noreply.github.com>

diff --git a/.github/workflows/push_trigger.yaml b/.github/workflows/push_trigger.yaml
--- a/.github/workflows/push_trigger.yaml
+++ b/.github/workflows/push_trigger.yaml
@@ -67,7 +67,8 @@ jobs:
                     echo "Pullpath: $fullpath"
                     fullname=$(basename "$line")
                     echo "Filename: $fullname"
-                  if [[ ! -d charts/$fullpath/ ]]; then echo "chart directory in list 'tmp.txt' not found; SKIPPING"; continue; fi
+                  if [[ ! -d charts/$fullpath/ ]]; then echo "chart directory fullpath in list 'tmp.txt' not found; SKIPPING"; continue; fi
+                  if [[ -z "$(ls -A charts/$fullpath/)" ]]; then echo "Helm chart directory is empty: charts/$fullpath/" exit 1; fi
                     helm dependency update charts/$fullpath/
                     helm package charts/$fullpath
                   done < tmp.txt
