[DSD-2733] added the env variable

diff --git a/.github/workflows/push_trigger.yaml b/.github/workflows/push_trigger.yaml
--- a/.github/workflows/push_trigger.yaml
+++ b/.github/workflows/push_trigger.yaml
@@ -61,18 +61,18 @@ jobs:
                   #find * -prune -type d > ../tmp.txt
                   #cd ..
                 
-                while IFS= read -r line
-                do
-                  fullpath=$line
-                  echo "Pullpath: $fullpath"
-                  fullname=$(basename "$line")
-                  echo "Filename: $fullname"
-                if [[ ! -d $fullpath/ ]]; then echo "chart directory $fullpath in list 'tmp.txt' not found; SKIPPING"; continue; fi
-                  helm dependency update $fullpath/
-                  helm package $fullpath
-                done < tmp.txt
-                if ! ls *.tgz 1> /dev/null 2>&1; then echo "no tar files generated"; fi
-                echo "env.SKIP=FALSE" >> $GITHUB_ENV
+                  while IFS= read -r line
+                  do
+                    fullpath=$line
+                    echo "Pullpath: $fullpath"
+                    fullname=$(basename "$line")
+                    echo "Filename: $fullname"
+                    if [[ ! -d $fullpath/ ]]; then echo "chart directory $fullpath in list 'tmp.txt' not found; SKIPPING"; continue; fi
+                    helm dependency update $fullpath/
+                    helm package $fullpath
+                  done < tmp.txt
+                    if ! ls *.tgz 1> /dev/null 2>&1; then echo "no tar files generated"; fi
+                    echo "env.SKIP=FALSE" >> $GITHUB_ENV
 
             - name: Upload tar as Artifact
               uses: actions/upload-artifact@v2
